{"name": "Test to get order list by logged in user", "status": "failed", "statusDetails": {"message": "AssertionError: assert 41468 == 1", "trace": "self = <tests.test_order.test_get_order_list.TestGetOrderList object at 0x1052f8230>\nget_ingredients = ['61c0c5a71d1f82001bdaaa6d', '61c0c5a71d1f82001bdaaa6f', '61c0c5a71d1f82001bdaaa70', '61c0c5a71d1f82001bdaaa71', '61c0c5a71d1f82001bdaaa72', '61c0c5a71d1f82001bdaaa6e', ...]\nprepare_user = <function prepare_user.<locals>._prepare_user at 0x1052eade0>\n\n    @allure.title('Test to get order list by logged in user')\n    @allure.description('Get order list by with user authorization positive check')\n    def test_get_orders_with_authorization_token(self, get_ingredients, prepare_user):\n        new_user = generate_user_data()\n        (_, token) = prepare_user(new_user)\n    \n        new_order = Order(get_ingredients[0:3])\n        OrderClient().create_order(new_order, token)\n    \n        (data, status_code) = OrderClient().get_order_list(token)\n    \n        assert status_code == requests.codes['ok']\n        assert data['success'] == True\n>       assert data['total'] == 1\nE       assert 41468 == 1\n\ntests/test_order/test_get_order_list.py:24: AssertionError"}, "description": "Get order list by with user authorization positive check", "start": 1708895312442, "stop": 1708895314075, "uuid": "cd46f600-38a7-4bc6-94dc-a3c6660cae8c", "historyId": "389a2d1ccd57a5e743fab7207755d1d6", "testCaseId": "389a2d1ccd57a5e743fab7207755d1d6", "fullName": "tests.test_order.test_get_order_list.TestGetOrderList#test_get_orders_with_authorization_token", "labels": [{"name": "parentSuite", "value": "tests.test_order"}, {"name": "suite", "value": "test_get_order_list"}, {"name": "subSuite", "value": "TestGetOrderList"}, {"name": "host", "value": "Air-Uchiru-5.lan"}, {"name": "thread", "value": "24222-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order.test_get_order_list"}]}